---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-hbase-zncdata-dev-v1alpha1-hbasecluster
  failurePolicy: Fail
  name: mhbasecluster.kb.io
  rules:
  - apiGroups:
    - hbase.zncdata.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hbaseclusters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-hbase-zncdata-dev-v1alpha1-hbasecluster
  failurePolicy: Fail
  name: vhbasecluster.kb.io
  rules:
  - apiGroups:
    - hbase.zncdata.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - hbaseclusters
  sideEffects: None
