# permissions for end users to view hbaseclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hbasecluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hbase-operator
    app.kubernetes.io/part-of: hbase-operator
    app.kubernetes.io/managed-by: kustomize
  name: hbasecluster-viewer-role
rules:
- apiGroups:
  - hbase.zncdata.dev
  resources:
  - hbaseclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hbase.zncdata.dev
  resources:
  - hbaseclusters/status
  verbs:
  - get
